# Obter a lista de usuários
GET http://localhost:3000/api/andamentos
Content-Type: application/json
###

# Inserir nova andamento
POST http://localhost:3000/api/andamentos
Content-Type: application/json
//x-auth-token: {{authToken}}

{
 "dataHora": "2020-11-25T17:32:25.000Z",
 "titulo": "Projeto dois",
 "descricao": "Não terminou",
 "responsavel1": "62471ca99f8cbc18824387e3",
 "responsavel2": "62471a6ca2f2fac13cd44332",
}
###

# Alterar andamento
PUT http://localhost:3000/api/andamentos
Content-Type: application/json

{
 "_id": "6247223e394e42882b848cc9",
 "dataHora": "2020-11-25T17:32:25.000Z",
 "titulo": "Projeto dois",
 "descricao": "Não terminou",
 "responsavel1": "62471ca99f8cbc18824387e3",
 "responsavel2": "62471a6ca2f2fac13cd44332",
}
###

# Excluir um andamento
DELETE http://localhost:3000/api/andamentos/6247235c394e42882b848cd8
Content-Type: application/json
###

# Obter pelo id de andamento
GET http://localhost:3000/api/andamentos/6247223e394e42882b848cc9
Content-Type: application/json
###

# Obter andamento filtrando
GET http://localhost:3000/api/andamentos/filtro/Projeto dois
Content-Type: application/json
###