# Obter a lista de usuários
GET http://localhost:3000/api/atividades
Content-Type: application/json
###

# Inserir nova atividade
POST http://localhost:3000/api/atividades
Content-Type: application/json
//x-auth-token: {{authToken}}

{
 "titulo": "Projeto dois",
 "descricao": "Fulano",
 "dataHoraCriada": "2020-11-25T17:32:25.000Z",
 "status": "Online",
 "prazo": "2020-11-25T17:32:25.000Z",
 "agendaInicio": "2020-11-25T17:32:25.000Z",
 "dataHoraTermino": "2020-11-25T17:32:25.000Z",
 "responsavel1": "62471ca99f8cbc18824387e3",
 "responsavel2": "62471a6ca2f2fac13cd44332",
}
###

# Alterar atividade
PUT http://localhost:3000/api/atividades
Content-Type: application/json

{
 "_id": "6247223e394e42882b848cc9",
 "titulo": "Projeto tres",
 "descricao": "Fulano",
 "dataHoraCriada": "2020-11-25T17:32:25.000Z",
 "status": "Online",
 "prazoAtendimento": "2020-11-25T17:32:25.000Z",
 "responsavel": "624720de394e42882b848cba",
 "responsavel": "62471a6ca2f2fac13cd44332",
}
###

# Excluir um atividade
DELETE http://localhost:3000/api/atividades/6247235c394e42882b848cd8
Content-Type: application/json
###

# Obter pelo id de atividade
GET http://localhost:3000/api/atividades/6247223e394e42882b848cc9
Content-Type: application/json
###

# Obter atividade filtrando
GET http://localhost:3000/api/atividades/filtro/Projeto dois
Content-Type: application/json
###