# Obter a lista de tiporequisicoes
GET http://localhost:3000/api/tiporequisicoes
Content-Type: application/json
###

# Inserir novo tiporequisicao
POST http://localhost:3000/api/tiporequisicoes
Content-Type: application/json

{
 "descricao": "Lapis de cor" 
}
###

# Alterar tiporequisicao
PUT http://localhost:3000/api/tiporequisicoes
Content-Type: application/json

{
 "_id": "62471cae9f8cbc18824387e5",
 "descricao": "Lapis colorido"
}
###

# Excluir um tiporequisicao
DELETE http://localhost:3000/api/tiporequisicoes/62471cae9f8cbc18824387e5
Content-Type: application/json
###

# Obter pelo id de tiporequisicao
GET http://localhost:3000/api/tiporequisicoes/62471cae9f8cbc18824387e5
Content-Type: application/json
###

# Obter tiporequisicao filtrando
GET http://localhost:3000/api/tiporequisicoes/filtro/Lapis
Content-Type: application/json
###